#!/usr/bin/env bash
#
# One-command installer for the VPN Config Store + Chat platform.
# Target: fresh Ubuntu/Debian server (also works on most systemd distros with Docker).
#
# Usage:
#   git clone <your-repo-url> vpn-platform && cd vpn-platform
#   sudo bash install.sh
#
set -euo pipefail

# ---------- helpers ----------
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}==>${NC} $1"; }
warn()  { echo -e "${YELLOW}!!${NC} $1"; }
err()   { echo -e "${RED}xx${NC} $1" >&2; }
gen()   { openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | base64 | tr -dc 'a-f0-9' | head -c64; }

ENV_FILE=".env"

# ---------- 0. root check ----------
if [ "$(id -u)" -ne 0 ]; then
  err "Please run as root (use: sudo bash install.sh)"; exit 1
fi

# ---------- 1. install Docker if missing ----------
if ! command -v docker >/dev/null 2>&1; then
  info "Docker not found — installing via get.docker.com ..."
  curl -fsSL https://get.docker.com | sh
else
  info "Docker already installed: $(docker --version)"
fi

# Compose plugin check
if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose plugin missing. Install 'docker-compose-plugin' and re-run."; exit 1
fi

systemctl enable --now docker >/dev/null 2>&1 || true

# ---------- 2. generate .env (idempotent — won't clobber existing) ----------
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — keeping it. Delete it and re-run to regenerate."
else
  info "Generating .env with fresh secrets ..."
  DB_PASS="$(gen | head -c 24)"
  read -rp "Public URL of your site (e.g. https://shop.example.com) [http://localhost]: " PUBLIC_URL
  PUBLIC_URL="${PUBLIC_URL:-http://localhost}"

  cat > "$ENV_FILE" <<EOF
# ---- auto-generated by install.sh on $(date -u +%FT%TZ) ----
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=vpnstore

JWT_ACCESS_SECRET=$(gen)
JWT_REFRESH_SECRET=$(gen)
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d

WEB_URL=${PUBLIC_URL}

# ---- Object storage (fill in for media uploads) ----
S3_ENDPOINT=
S3_BUCKET=vpn-media
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_PUBLIC_URL=

# ---- Telegram bot (optional; wired later) ----
TELEGRAM_BOT_TOKEN=
TELEGRAM_ADMIN_CHAT_ID=
EOF
  chmod 600 "$ENV_FILE"
  info ".env created (permissions 600). Secrets generated automatically."
fi

# ---------- 3. build & launch ----------
info "Building images (first run takes a few minutes) ..."
docker compose build

info "Starting the stack ..."
docker compose up -d

# ---------- 4. run DB migrations ----------
info "Waiting for Postgres to be healthy ..."
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U postgres >/dev/null 2>&1; then break; fi
  sleep 2
done

info "Applying database schema (prisma migrate deploy) ..."
docker compose run --rm api sh -c "cd packages/db && npx prisma migrate deploy" \
  || warn "Migration step skipped/failed — run it manually once migrations exist."

# ---------- 5. done ----------
echo ""
info "Installation complete."
echo "  Web:   ${PUBLIC_URL:-http://localhost}"
echo "  API:   ${PUBLIC_URL:-http://localhost}/api/health"
echo ""
echo "Useful commands:"
echo "  docker compose ps          # status"
echo "  docker compose logs -f     # live logs"
echo "  docker compose down        # stop"
echo "  docker compose up -d       # start"
