#!/usr/bin/env bash
# Installer for Ubuntu 24.04. Existing .env files are never overwritten.
set -Eeuo pipefail
umask 077

ENV_FILE="${ENV_FILE:-.env}"

info() { printf '\033[0;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*"; }
die() { printf '\033[0;31mxx\033[0m %s\n' "$*" >&2; exit 1; }
secret() { openssl rand -hex 32; }

if [ "$(id -u)" -ne 0 ]; then
  die "Run as root: sudo ./install.sh"
fi

export DEBIAN_FRONTEND=noninteractive
if ! command -v docker >/dev/null 2>&1; then
  info "Installing Docker Engine and Compose plugin"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl openssl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  . /etc/os-release
  [ "${ID:-}" = "ubuntu" ] || die "Automatic Docker installation supports Ubuntu only"
  printf 'Types: deb\nURIs: https://download.docker.com/linux/ubuntu\nSuites: %s\nComponents: stable\nArchitectures: %s\nSigned-By: /etc/apt/keyrings/docker.asc\n' \
    "${UBUNTU_CODENAME:-$VERSION_CODENAME}" "$(dpkg --print-architecture)" \
    > /etc/apt/sources.list.d/docker.sources
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  info "Using $(docker --version)"
fi

docker compose version >/dev/null 2>&1 || die "Docker Compose v2 plugin is required"
systemctl enable --now docker >/dev/null

if [ -f "$ENV_FILE" ]; then
  chmod 600 "$ENV_FILE"
  info "Keeping existing $ENV_FILE"
else
  command -v openssl >/dev/null 2>&1 || { apt-get update -qq; apt-get install -y -qq openssl; }

  PUBLIC_URL="${PUBLIC_URL:-http://localhost}"
  ADMIN_USERNAME_VALUE="${ADMIN_USERNAME:-admin}"
  ADMIN_PASSWORD_VALUE="${ADMIN_PASSWORD:-}"
  TELEGRAM_TOKEN_VALUE="${TELEGRAM_BOT_TOKEN:-}"
  TELEGRAM_CHAT_VALUE="${TELEGRAM_ADMIN_CHAT_ID:-}"

  if [ -t 0 ] && [ -t 1 ]; then
    read -r -p "Public URL [${PUBLIC_URL}]: " answer
    PUBLIC_URL="${answer:-$PUBLIC_URL}"
    read -r -p "Admin username [${ADMIN_USERNAME_VALUE}]: " answer
    ADMIN_USERNAME_VALUE="${answer:-$ADMIN_USERNAME_VALUE}"
    while [ -z "$ADMIN_PASSWORD_VALUE" ]; do
      read -r -s -p "Admin password (12+ characters): " ADMIN_PASSWORD_VALUE
      printf '\n'
      [ "${#ADMIN_PASSWORD_VALUE}" -ge 12 ] || { warn "Password is too short"; ADMIN_PASSWORD_VALUE=""; }
    done
    read -r -p "Telegram bot token (optional, press Enter to skip): " TELEGRAM_TOKEN_VALUE
    read -r -p "Telegram admin chat ID (optional, press Enter to skip): " TELEGRAM_CHAT_VALUE
  elif [ -z "$ADMIN_PASSWORD_VALUE" ]; then
    ADMIN_PASSWORD_VALUE="$(secret)"
    warn "No terminal/ADMIN_PASSWORD supplied; generated the admin password in $ENV_FILE"
  fi

  [[ "$PUBLIC_URL" =~ ^https?://[^[:space:]]+$ ]] || die "PUBLIC_URL must be an http(s) URL without spaces"
  [[ "$ADMIN_USERNAME_VALUE" =~ ^[A-Za-z0-9_]{3,32}$ ]] || die "ADMIN_USERNAME must be 3-32 letters, digits, or underscores"
  [ "${#ADMIN_PASSWORD_VALUE}" -ge 12 ] || die "ADMIN_PASSWORD must be at least 12 characters"

  info "Creating $ENV_FILE with generated database and JWT secrets"
  {
    printf '# Generated by install.sh on %s\n' "$(date -u +%FT%TZ)"
    printf 'POSTGRES_USER=postgres\nPOSTGRES_PASSWORD=%s\nPOSTGRES_DB=vpnstore\n\n' "$(secret)"
    printf 'JWT_ACCESS_SECRET=%s\nJWT_ACCESS_TTL=15m\nJWT_REFRESH_TTL=7d\n\n' "$(secret)"
    printf 'ADMIN_USERNAME=%s\nADMIN_PASSWORD=%s\n\n' "$ADMIN_USERNAME_VALUE" "$ADMIN_PASSWORD_VALUE"
    printf 'WEB_URL=%s\nHTTP_PORT=80\nNEXT_PUBLIC_API_URL=/api\n\n' "$PUBLIC_URL"
    printf 'S3_ENDPOINT=\nS3_BUCKET=\nS3_ACCESS_KEY_ID=\nS3_SECRET_ACCESS_KEY=\nS3_PUBLIC_URL=\n\n'
    printf 'TELEGRAM_BOT_TOKEN=%s\nTELEGRAM_ADMIN_CHAT_ID=%s\n' "$TELEGRAM_TOKEN_VALUE" "$TELEGRAM_CHAT_VALUE"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

info "Building application images"
docker compose build
info "Starting database and Redis"
docker compose up -d postgres redis
info "Applying database migrations"
docker compose run --rm migrate
info "Starting the application"
docker compose up -d --remove-orphans

if docker compose ps --format json >/dev/null 2>&1; then
  docker compose ps
fi
info "Installation complete. Check health with: docker compose ps"
